// <auto-generated />
using FurnitureShop.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FurnitureShop.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220513202354_Categories")]
    partial class Categories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FurnitureShop.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Living Room Furniture",
                            Url = "living_room_furniture"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bedroom Furniture",
                            Url = "bedroom_furniture"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kitchen & Dinning Furniture",
                            Url = "kitchen_&_dinning_furniture"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Office Furniture",
                            Url = "office_furniture"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bathroom Furniture",
                            Url = "bathroom_furniture"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kids Furniture",
                            Url = "kids_furniture"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Game Room Furniture",
                            Url = "game_room_furniture"
                        });
                });

            modelBuilder.Entity("FurnitureShop.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Description1",
                            ImageUrl = "#",
                            Price = 9.99m,
                            Title = "Title1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Description2",
                            ImageUrl = "#",
                            Price = 7.99m,
                            Title = "Title2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Description3",
                            ImageUrl = "#",
                            Price = 6.99m,
                            Title = "Title3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Description4",
                            ImageUrl = "#",
                            Price = 5.99m,
                            Title = "Title4"
                        });
                });

            modelBuilder.Entity("FurnitureShop.Shared.Product", b =>
                {
                    b.HasOne("FurnitureShop.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
